/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package duarte.programacion2.finalproject.series.PnlAnualidades;

import javax.swing.ButtonGroup;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author dell
 */
public class PnlAnualidadTemplate extends javax.swing.JInternalFrame {

    /**
     * Creates new form PnlAnualidadTemplate
     */
    public PnlAnualidadTemplate() {
        initComponents();
    }

    public ButtonGroup getBtngTasa() {
        return btngTasa;
    }

    public ButtonGroup getBtngValor() {
        return btngValor;
    }

    public JComboBox<String> getCmbPeriodos() {
        return cmbPeriodos;
    }

    public JComboBox<String> getCmbTipoPeriodica() {
        return cmbTipoPeriodica;
    }

    public JFormattedTextField getFmdtResultado() {
        return fmdtResultado;
    }

    public JRadioButton getRbtnAnual() {
        return rbtnAnual;
    }

    public JRadioButton getRbtnPeriodica() {
        return rbtnPeriodica;
    }

    public JRadioButton getRbtnVF() {
        return rbtnVF;
    }

    public JRadioButton getRbtnVP() {
        return rbtnVP;
    }

    public JTextField getTxtPeriodos() {
        return txtPeriodos;
    }

    public JTextField getTxtTasa() {
        return txtTasa;
    }

    public JTextField getTxtValor() {
        return txtValor;
    }

    public JLabel getLblProcentaje() {
        return lblProcentaje;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btngValor = new javax.swing.ButtonGroup();
        btngTasa = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rbtnVP = new javax.swing.JRadioButton();
        rbtnVF = new javax.swing.JRadioButton();
        txtValor = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        rbtnAnual = new javax.swing.JRadioButton();
        rbtnPeriodica = new javax.swing.JRadioButton();
        cmbTipoPeriodica = new javax.swing.JComboBox<>();
        lblProcentaje = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        cmbPeriodos = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        fmdtResultado = new javax.swing.JFormattedTextField();
        txtTasa = new javax.swing.JTextField();
        txtPeriodos = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setPreferredSize(new java.awt.Dimension(600, 600));

        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Valor (pago)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        btngValor.add(rbtnVP);
        rbtnVP.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        rbtnVP.setText("Valor Presente (P)");
        rbtnVP.setNextFocusableComponent(rbtnVF);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 17;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 82, 0, 0);
        jPanel1.add(rbtnVP, gridBagConstraints);

        btngValor.add(rbtnVF);
        rbtnVF.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        rbtnVF.setText("Valor Futuro (F)");
        rbtnVF.setNextFocusableComponent(rbtnAnual);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 82, 0, 0);
        jPanel1.add(rbtnVF, gridBagConstraints);

        txtValor.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtValor.setForeground(java.awt.Color.gray);
        txtValor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtValor.setText("Digite el Valor");
        txtValor.setEnabled(false);
        txtValor.setNextFocusableComponent(txtTasa);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 24;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 78;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 145;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 40, 0, 0);
        jPanel1.add(txtValor, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 238;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 475;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 12, 0, 12);
        jPanel1.add(jSeparator1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Tasa de interes (i)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        btngTasa.add(rbtnAnual);
        rbtnAnual.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        rbtnAnual.setText("Efectiva anual");
        rbtnAnual.setNextFocusableComponent(txtTasa);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 83, 0, 0);
        jPanel1.add(rbtnAnual, gridBagConstraints);

        btngTasa.add(rbtnPeriodica);
        rbtnPeriodica.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        rbtnPeriodica.setText("Efectiva Periodica");
        rbtnPeriodica.setNextFocusableComponent(cmbTipoPeriodica);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 83, 0, 0);
        jPanel1.add(rbtnPeriodica, gridBagConstraints);

        cmbTipoPeriodica.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cmbTipoPeriodica.setEnabled(false);
        cmbTipoPeriodica.setNextFocusableComponent(txtTasa);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 24;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 22;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 89;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel1.add(cmbTipoPeriodica, gridBagConstraints);

        lblProcentaje.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblProcentaje.setText("%");
        lblProcentaje.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 236;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 3, 0, 0);
        jPanel1.add(lblProcentaje, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 238;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 475;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 12);
        jPanel1.add(jSeparator2, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Periodos (n)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 0, 0);
        jPanel1.add(jLabel4, gridBagConstraints);

        cmbPeriodos.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 45;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 134;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 89;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 18, 0, 0);
        jPanel1.add(cmbPeriodos, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 238;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 475;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 12);
        jPanel1.add(jSeparator3, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Anualidad (A)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 0, 0);
        jPanel1.add(jLabel5, gridBagConstraints);

        fmdtResultado.setEditable(false);
        fmdtResultado.setForeground(java.awt.Color.gray);
        fmdtResultado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        fmdtResultado.setText("NaN");
        fmdtResultado.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.gridwidth = 57;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 145;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 5, 12, 0);
        jPanel1.add(fmdtResultado, gridBagConstraints);

        txtTasa.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtTasa.setForeground(java.awt.Color.gray);
        txtTasa.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTasa.setText("Digite la Tasa");
        txtTasa.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 101;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 135;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 85;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 32, 0, 0);
        jPanel1.add(txtTasa, gridBagConstraints);

        txtPeriodos.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtPeriodos.setForeground(java.awt.Color.gray);
        txtPeriodos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPeriodos.setText("N° de Periodos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 21;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 85;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 46, 0, 0);
        jPanel1.add(txtPeriodos, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btngTasa;
    private javax.swing.ButtonGroup btngValor;
    private javax.swing.JComboBox<String> cmbPeriodos;
    private javax.swing.JComboBox<String> cmbTipoPeriodica;
    private javax.swing.JFormattedTextField fmdtResultado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblProcentaje;
    private javax.swing.JRadioButton rbtnAnual;
    private javax.swing.JRadioButton rbtnPeriodica;
    private javax.swing.JRadioButton rbtnVF;
    private javax.swing.JRadioButton rbtnVP;
    private javax.swing.JTextField txtPeriodos;
    private javax.swing.JTextField txtTasa;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
