/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package duarte.programacion2.finalproject.series.mainFrm;

import duarte.programacion2.finalproject.series.mainFrm.controller.FrmSeriesController;
import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

/**
 *
 * @author ElChamoLeo
 */
public class FrmSeries extends javax.swing.JFrame {

    /**
     * Creates new form FrmSeries
     */
    
    private final FrmSeriesController controller;
    
    public FrmSeries() {
        initComponents();
        controller = new FrmSeriesController(this);
    }

    public JDesktopPane getDkpMainConteiner() {
        return dkpMainConteiner;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public JMenuItem getMniAnticipada() {
        return mniAnticipada;
    }

    public JMenuItem getMniDiferida() {
        return mniDiferida;
    }

    public JMenuItem getMniGAritmetico() {
        return mniGAritmetico;
    }

    public JMenuItem getMniGGeometrico() {
        return mniGGeometrico;
    }

    public JMenuItem getMniOrdinaria() {
        return mniOrdinaria;
    }

    public JMenuItem getMniPerpetua() {
        return mniPerpetua;
    }

    public JMenu getMnuAnualidades() {
        return mnuAnualidades;
    }

    public JMenu getMnuSeries() {
        return mnuSeries;
    }

    public JMenu getMnuSeriesG() {
        return mnuSeriesG;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dkpMainConteiner = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuSeries = new javax.swing.JMenu();
        mnuAnualidades = new javax.swing.JMenu();
        mniOrdinaria = new javax.swing.JMenuItem();
        mniAnticipada = new javax.swing.JMenuItem();
        mniDiferida = new javax.swing.JMenuItem();
        mniPerpetua = new javax.swing.JMenuItem();
        mnuSeriesG = new javax.swing.JMenu();
        mniGAritmetico = new javax.swing.JMenuItem();
        mniGGeometrico = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout dkpMainConteinerLayout = new javax.swing.GroupLayout(dkpMainConteiner);
        dkpMainConteiner.setLayout(dkpMainConteinerLayout);
        dkpMainConteinerLayout.setHorizontalGroup(
            dkpMainConteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        dkpMainConteinerLayout.setVerticalGroup(
            dkpMainConteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        getContentPane().add(dkpMainConteiner, java.awt.BorderLayout.CENTER);

        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        mnuSeries.setText("Series");
        mnuSeries.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        mnuAnualidades.setText("Anualidades");
        mnuAnualidades.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        mniOrdinaria.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        mniOrdinaria.setText("Ordinaria");
        mnuAnualidades.add(mniOrdinaria);

        mniAnticipada.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        mniAnticipada.setText("Anticipada");
        mnuAnualidades.add(mniAnticipada);

        mniDiferida.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        mniDiferida.setText("Diferida");
        mnuAnualidades.add(mniDiferida);

        mniPerpetua.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        mniPerpetua.setText("Perpetua");
        mnuAnualidades.add(mniPerpetua);

        mnuSeries.add(mnuAnualidades);

        mnuSeriesG.setText("Series con gradientes ");
        mnuSeriesG.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        mniGAritmetico.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        mniGAritmetico.setText("Gradiente Aritmetico");
        mnuSeriesG.add(mniGAritmetico);

        mniGGeometrico.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        mniGGeometrico.setText("Gradiente Geometrico");
        mnuSeriesG.add(mniGGeometrico);

        mnuSeries.add(mnuSeriesG);
        mnuSeries.add(jSeparator1);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jMenuItem1.setText("Salir");
        mnuSeries.add(jMenuItem1);

        jMenuBar1.add(mnuSeries);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSeries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSeries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSeries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSeries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSeries().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dkpMainConteiner;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem mniAnticipada;
    private javax.swing.JMenuItem mniDiferida;
    private javax.swing.JMenuItem mniGAritmetico;
    private javax.swing.JMenuItem mniGGeometrico;
    private javax.swing.JMenuItem mniOrdinaria;
    private javax.swing.JMenuItem mniPerpetua;
    private javax.swing.JMenu mnuAnualidades;
    private javax.swing.JMenu mnuSeries;
    private javax.swing.JMenu mnuSeriesG;
    // End of variables declaration//GEN-END:variables
}
